server:
  port: 8184

spring:
  application:
    name: product
  data:
      mongodb:
        host: localhost
        port: 27017
        database: product
        repositories:
          enabled: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8661/eureka
    instances:
      hostname: localhost