server:
  port: 8183

spring:
  application:
    name: user
  data:
    mongodb:
      host: localhost
      port: 27017
      database: user
      repositories:
        enabled: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8661/eureka
    instances:
      hostname: localhost